twig:
    default_path: '%kernel.project_dir%/templates'
   
    form_themes:
        - bootstrap_4_layout.html.twig

when@test:
    twig:
        strict_variables: true
  
  default_path: "%kernel.project_dir%/templates"
  globals:
    # the value is the service's id
    hasVoiture: "false"
when@test:
  twig:
    strict_variables: true
